const api = 
[
    { "name": "Pizza", "price": 10.99 },
    { "name": "Burger", "price": 6.49 },
    { "name": "Salad", "price": 5.99 },
    { "name": "Pasta", "price": 8.75 },
    { "name": "Steak", "price": 15.50 },
    { "name": "Sushi", "price": 12.25 },
    { "name": "Fried Chicken", "price": 9.99 },
    { "name": "Taco", "price": 4.75 },
    { "name": "Fish and Chips", "price": 11.50 },
    { "name": "Soup", "price": 4.25 },
    { "name": "Sandwich", "price": 7.50 },
    { "name": "Hot Dog", "price": 3.99 },
    { "name": "Curry", "price": 9.75 },
    { "name": "Ramen", "price": 8.25 },
    { "name": "Omelette", "price": 6.75 },
    { "name": "Shrimp Scampi", "price": 13.99 },
    { "name": "Chicken Caesar Salad", "price": 10.25 },
    { "name": "Miso Soup", "price": 3.50 },
    { "name": "Pancakes", "price": 5.75 },
    { "name": "Lasagna", "price": 12.99 },
    { "name": "Dim Sum", "price": 8.99 },
    { "name": "Hamburger", "price": 6.99 },
    { "name": "Fajitas", "price": 9.25 },
    { "name": "Pho", "price": 7.50 },
    { "name": "Caesar Salad", "price": 6.25 },
    { "name": "Gyoza", "price": 5.50 },
    { "name": "Chicken Wings", "price": 8.49 },
    { "name": "Tuna Sandwich", "price": 7.25 },
    { "name": "Meatball Sub", "price": 6.75 },
    { "name": "Shrimp Fried Rice", "price": 11.99 },
    { "name": "Chicken Noodle Soup", "price": 4.75 },
    { "name": "Calzone", "price": 8.99 },
    { "name": "Ceviche", "price": 12.75 },
    { "name": "Chicken Teriyaki", "price": 10.50 },
    { "name": "Egg Fried Rice", "price": 6.99 },
    { "name": "Spaghetti Bolognese", "price": 9.99 },
    { "name": "Shawarma", "price": 7.75 },
    { "name": "Fish Tacos", "price": 10.25 },
    { "name": "Veggie Burger", "price": 8.50 },
    { "name": "Chicken Fried Rice", "price": 9.99 },
    { "name": "Cheese Quesadilla", "price": 5.99 }
  ]
  
export default api;